### ISSUE TITLE
Gamification System

### ISSUE THREAD

**Issue by thelastinuit** [IcaliaLabs/epick#13]
The gem we're going to use is [this one](https://github.com/thelastinuit/gioco/tree/1.1.1).  The setup is done already.

Any issue with the gem will be resolved at that fork.

Please branch out from `development` branch.

**Comment by kurenn** [comment]
The gem looks cool, there is also another [one] (https://github.com/joaomdmoura/gioco) I used it in the past, and it is not bad, but I can imagine you saw that already

**Comment by thelastinuit** [comment]
I did it. But the 0.1.1 version is buggy since Joao started to migrate to a new version. I think something happened and he hasn't noticed. I thought of fixing the issue but time is of gold right now..
