### ISSUE TITLE
As teacher I can create a course

### ISSUE THREAD

**Issue by thelastinuit** [IcaliaLabs/epick#5]
Teacher should be:

*Course*
- [x] To create a course.
- [x] To add a course description.
- [x] To add a course name.
- [x] To add a course objectives. Bear in mind this an array behind the courtain.

*Section*
- [x] To add a section.

*Resource* 
- [x] To add resources to a section.
- [x] To add a link to a resource.

*Activity*
- [x] To add activites to a section.
- [x] To add activity title.
- [x] To add activity description.
- [x] To add activity url.
- [x] To add questions to an acvitity

*Exam*
- [x] To add an exam to a section.
- [x] To add exam description.
- [x] To add questions to exam.

This works needs to be done in the frontend. The `courses` controller has basic funcionality.
All the views are under `app/views/courses/*`. The form needs to be cooked up in a way it can be handle easily in the backend. I.e. under ´db/seeds.rb´:

```ruby
data = CourseBuilder.create "Dynamics of the Spacetime Continuum" do
  description "How the Spacetime Continuum works? In this course will see through all the mysterios of the matter."
  objective "Understand the basic of QED"
  objective "QED with differente metrics"

  section "QED: 101" do
    resource "Quantum Field Theory" do
      link "https://www.youtube.com/watch?v=j-BznRQbT4Y"
    end

    resource "Quantum Electrodynamics" do
      link "https://www.youtube.com/watch?v=hHTWBc14-mk"
    end

    activity "Physics of Fields" do
      description "Please read the following paper"
      url "https://arxiv.org/pdf/1609.01496.pdf"
      question "How does the quantized massless Klein-Gordon field works on the Politzer spacetime?"
    end

    exam do
      description "Please review the resources and activies given before."
      question "How can we cheat quantum communication with backward time-steps?"
      question "Is it possible to create a non-negative metric that allow us quantum communication at room temperature?"
    end
  end
end

Course.create data
```

With the right params once in the controller, we can create a course easily.

The branch for such issue is `feature/create-course`

**Comment by kurenn** [comment]
I love the DSL, let's see how it works

**Comment by thelastinuit** [comment]
works fine, we now just need to arrange the form in a way that allow us to use the dsl.
